  <footer class="page-footer red darken-4">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
              <h5 class="white-text">Thanks for checking out my site!</h5>
              <p class="grey-text text-lighten-4">Come again soon.</p>
            </div>
            <div class="col l4 offset-l2 s12">
              <h5 class="white-text">Links</h5>
              <ul>
                <li><a class="grey-text text-lighten-3" href="https://www.linkedin.com/in/michelle-bushoy-725730137/" target="_blank">LinkedIn</a></li>
                <li><a class="grey-text text-lighten-3" href="https://github.com/mbushoy27" target="_blank" >GitHub</a></li>
                <li><a class="grey-text text-lighten-3" href="images/resume.pdf" target="_blank">Resume</a></li>
              </ul>
            </div>
          </div>
      </div>
      <div class="footer-copyright">
        <div class="container">Michelle Bushoy © 2017 Copyright</div>
      </div>
    </footer>