<!-- Nav bar -->
<div class="navbar-fixed">
  <nav class="red darken-4" role="navigation">
    <div class="nav-wrapper container">
      <ul class="right hide-on-med-and-down">
        <li><a href="index.php#code" class="white-text">Code</a></li>
        <li><a href="index.php#design" class="white-text">Design</a></li>
      </ul>
      <ul class="left hide-on-med-and-down">
        <li><a href="index.php" class="white-text">Home</a></li>
      </ul>

<!-- Nav bar for mobile -->
      <ul id="nav-mobile" class="side-nav">
        <li><a href="index.php">Home</a></li>
        <li><a href="index.php#code">Code</a></li>
        <li><a href="index.php#design">Design</a></li>
      </ul>
    </div>
  </nav>
  </div>
<!-- End nav -->